package com.food.autoIdcontroller;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.food.db.MyConnection;

@CrossOrigin(origins = "http://localhost:4200")
@RestController
public class AutoIdController {

    @GetMapping(value="/api/getAutoGeneratedId")
    public String getAutoGeneratedId(
            @RequestParam String tableName,
            @RequestParam String idName,
            @RequestParam String word
    ) {
        // Move the autoIdGenated method here
        try {
            Connection con = MyConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("SELECT MAX(" + idName + ") FROM " + tableName);
            ResultSet set = pst.executeQuery();

            while (set.next()) {
                String maxId = set.getString(1);

                if (maxId == null) {
                    return "" + word + "0000001";
                } else {
                    long id = Long.parseLong(maxId.substring(word.length()));
                    id++;
                    return "" + word + String.format("%07d", id);
                }
            }

            // Close the resources
            set.close();
            pst.close();
            con.close();

        } catch (NumberFormatException | SQLException ex) {
            ex.printStackTrace();
        }

        return "";
    }
}
